"""init

Revision ID: d1acd8030258
Revises: 
Create Date: 2024-11-17 20:09:05.287847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1acd8030258"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("thematickblock", sa.Boolean(), nullable=False),
        sa.Column("publication", sa.Boolean(), nullable=False),
        sa.Column("comments", sa.Boolean(), nullable=False),
        sa.Column("event", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("admin_id"),
    )
    op.create_table(
        "articles",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("stop_description", sa.String(), nullable=False),
        sa.Column("interval", sa.String(), nullable=False),
        sa.Column("time_in", sa.String(), nullable=False),
        sa.Column("time_out", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "folders",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publications",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("media", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "thematic_blocks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("time_back", sa.Integer(), nullable=False),
        sa.Column("stop_words", sa.String(), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publication_schedule",
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("ind_pub_id", sa.Integer(), nullable=True),
        sa.Column("thematic_block_id", sa.Integer(), nullable=False),
        sa.Column("today", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["ind_pub_id"],
            ["publications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thematic_block_id"],
            ["thematic_blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_schedule")
    op.drop_table("thematic_blocks")
    op.drop_table("publications")
    op.drop_table("folders")
    op.drop_table("events")
    op.drop_table("articles")
    op.drop_table("admins")
    # ### end Alembic commands ###
